### ISSUE TITLE
Add support for other elytra-like items from other mods

### ISSUE THREAD

**Issue by InsaanNotFound** [CafeteriaGuild/FFL-Trinkets-Compat#1]
There are elytra based items that do not work, even with fix:
Armored Elytra - Better End
Netherite Elytra - Netherite Plus
Winged Chestplate - Dragon Loot

**Comment by NotJustAnna** [comment]
This mod is not intended to fix the compatibility with any other mod but Trinkets.

**Comment by NotJustAnna** [comment]
Issues were opened asking the mods to support FFL.

**Comment by InsaanNotFound** [comment]
@adriantodt also issue seems to touch mods like Customizable Elytra etc

**Comment by NotJustAnna** [comment]
Customizable Elytra uses Caelus, which is currently not supported by FFL.
